import { FieldRuleEnum, FieldTypeEnum } from '@lib/shared/enums/formDesignEnum';
import type { SaveInvoiceMaterialParams } from '@lib/shared/models/contract';

import type { FormCreateField } from '@/components/business/crm-form-create/types';

export const initInvoiceMaterialForm: SaveInvoiceMaterialParams = {
  id: '',
  hospitalName: '',
  invoice: '',
  verificationProof: '',
  sampleMailing: '',
  samplePhoto: '',
  report: '',
  outboundOrder: '',
  contract: '',
  platform: '',
  otherMaterials: '',
};

export const yesNoOptions = [
  { label: '是', value: '是' },
  { label: '否', value: '否' },
];

export const platformOptions = [
  { label: '喀斯码', value: '喀斯码' },
  { label: '锐竞', value: '锐竞' },
  { label: '医院平台', value: '医院平台' },
  { label: '无', value: '无' },
];

export const invoiceMaterialFieldList: FormCreateField[] = [
  {
    id: 'hospitalName',
    businessKey: 'hospitalName',
    name: 'contract.invoiceMaterial.hospitalName',
    type: FieldTypeEnum.INPUT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [
      { key: FieldRuleEnum.REQUIRED, required: true, message: 'contract.invoiceMaterial.hospitalNamePlaceholder' },
    ],
    icon: '',
    fieldWidth: 1,
  },
  {
    id: 'invoice',
    businessKey: 'invoice',
    name: 'contract.invoiceMaterial.invoice',
    type: FieldTypeEnum.SELECT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 0.5,
    options: yesNoOptions,
  },
  {
    id: 'verificationProof',
    businessKey: 'verificationProof',
    name: 'contract.invoiceMaterial.verificationProof',
    type: FieldTypeEnum.SELECT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 0.5,
    options: yesNoOptions,
  },
  {
    id: 'sampleMailing',
    businessKey: 'sampleMailing',
    name: 'contract.invoiceMaterial.sampleMailing',
    type: FieldTypeEnum.SELECT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 0.5,
    options: yesNoOptions,
  },
  {
    id: 'samplePhoto',
    businessKey: 'samplePhoto',
    name: 'contract.invoiceMaterial.samplePhoto',
    type: FieldTypeEnum.SELECT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 0.5,
    options: yesNoOptions,
  },
  {
    id: 'report',
    businessKey: 'report',
    name: 'contract.invoiceMaterial.report',
    type: FieldTypeEnum.SELECT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 0.5,
    options: yesNoOptions,
  },
  {
    id: 'outboundOrder',
    businessKey: 'outboundOrder',
    name: 'contract.invoiceMaterial.outboundOrder',
    type: FieldTypeEnum.SELECT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 0.5,
    options: yesNoOptions,
  },
  {
    id: 'contract',
    businessKey: 'contract',
    name: 'contract.invoiceMaterial.contract',
    type: FieldTypeEnum.SELECT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 0.5,
    options: yesNoOptions,
  },
  {
    id: 'platform',
    businessKey: 'platform',
    name: 'contract.invoiceMaterial.platform',
    type: FieldTypeEnum.SELECT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 0.5,
    options: platformOptions,
  },
  {
    id: 'otherMaterials',
    businessKey: 'otherMaterials',
    name: 'contract.invoiceMaterial.otherMaterials',
    type: FieldTypeEnum.INPUT,
    showLabel: true,
    description: '',
    readable: true,
    editable: true,
    rules: [],
    icon: '',
    fieldWidth: 1,
  },
];
